# Basic dependabot.yml to update gomod & GitHub actions

version: 2
updates:
  - package-ecosystem: "gomod"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
    reviewers:
      - "mrz1836"
    assignees:
      - "mrz1836"
    labels:
      - "update"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "mrz1836"
    assignees:
      - "mrz1836"
    labels:
      - "chore"
    open-pull-requests-limit: 10